# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Automationhub < Formula
  desc "Automation Environment to run Unity3D PlayMode tests on real devices for android support install adb and aapt: brew install --cask android-sdk brew install --cask android-platform-tools"
  homepage "https://github.com/fsuhrau/automationhub"
  version "0.1.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fsuhrau/automationhub/releases/download/v0.1.2/automationhub_0.1.2_darwin_arm64.tar.gz"
      sha256 "e3ce87493e1ef972dcc46261075d73aa26cc1504f1305a6bf7820e723271d4c0"

      def install
        bin.install "hub"
        bin.install "hubcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fsuhrau/automationhub/releases/download/v0.1.2/automationhub_0.1.2_darwin_amd64.tar.gz"
      sha256 "05cdb147c43530ebb840959da5b414fb445688a0536d1d04b58778a83b2ee784"

      def install
        bin.install "hub"
        bin.install "hubcli"
      end
    end
  end

  def caveats
    <<~EOS
      hub configure # to get started
    EOS
  end
end
