# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopretty < Formula
  desc "Go Pretty a small beautifier for XCode builds similar to xcpretty"
  homepage "https://github.com/fsuhrau/gopretty"
  version "1.0.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/fsuhrau/gopretty/releases/download/v1.0.0/gopretty_1.0.0_darwin_amd64.tar.gz"
    sha256 "00a2d1d7c60474dfe2de5a7bb5bd2093eea51be026b43d9e1e98bf44d079fa82"

    def install
      bin.install "gopretty"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/fsuhrau/gopretty/releases/download/v1.0.0/gopretty_1.0.0_darwin_arm64.tar.gz"
    sha256 "cf1b1b5a4909627c8f3ec5dfd8795a121c388735b40c3e9fab4a0a5f25de5765"

    def install
      bin.install "gopretty"
    end
  end

  def caveats
    <<~EOS
      xcodebuild -project 'testproject.xcodeproj' -configuration Release -target "test" | gopretty
    EOS
  end
end
