# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gopretty < Formula
  desc "Go Pretty a small beautifier for XCode builds similar to xcpretty"
  homepage "https://github.com/fsuhrau/gopretty"
  version "0.2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fsuhrau/gopretty/releases/download/v0.2.0/gopretty_0.2.0_darwin_amd64.tar.gz"
      sha256 "9ac6c84ed4db2df17676ed86d6a3d48572e84a03073f5e29fa1caf978a5b4236"

      def install
        bin.install "gopretty"
      end
    end
  end

  def caveats; <<~EOS
    xcodebuild -project 'testproject.xcodeproj' -configuration Release -target "test" | gopretty
  EOS
  end
end
